proxy:
  image: nginx:alpine
  volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./proxy/server.crt:/etc/nginx/ssl/server.crt:ro
    - ./proxy/server.key:/etc/nginx/ssl/server.key:ro
  ports:
    - "443:443"
  links:
    - api

api:
  build: ./api
  ports:
    - "9900:9900"
