proxy:
  image: nginx:alpine
  volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt/live/www.olipicus.com/fullchain.pem:/etc/nginx/ssl/server.crt:ro
    - /etc/letsencrypt/live/www.olipicus.com/privkey.pem:/etc/nginx/ssl/server.key:ro
  ports:
    - "443:443"
  links:
    - api

api:
  build: ./api
  environment:
    - PORT=9900
    - CHANNEL_SECRET=d4a54c56a4711f297adc6f9e0eb1134d
    - CHANNEL_TOKEN=0pu52f1adC4VUlyXAnVVb3+dVoeFgEyS3yqXUzkfdw6tr4diek24GQAa2JNLPRFiH8b6vmHDVCTGqKrpB1DcqcVaDtGHj9cE5acil1LzUWxoSRsrkJxFgRu7XMtOGmiwOj6c8SsjvXvKWxN2r1aSigdB04t89/1O/w1cDnyilFU=
  ports:
    - "80:9900"