proxy:
  image: nginx:alpine
  volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt/live/www.olipicus.com/cert.pem:/etc/nginx/ssl/server.crt:ro
    - /etc/letsencrypt/live/www.olipicus.com/privkey.pem:/etc/nginx/ssl/server.key:ro
  ports:
    - "443:443"
  links:
    - api

api:
  build: ./api
  ports:
    - "80:9900"
